#!/bin/bash

ISMUTE=$(amixer get Master | awk '/Mono:/ {print $6}' | sed -e 's/\[//; s/\]//')
VOL=$(amixer get Master | awk '/Mono:/ {print $4}' | sed -e 's/\[//; s/\]//')

case $ISMUTE in
    on)
        echo  $VOL ;;
    off)
        echo ﱝ $VOL ;;
    *)
        ;;
esac
